/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MetroInterfaz;

/**
 *
 * @author ile1
 */
public class Loser extends javax.swing.JFrame {

    /**
     * Creates new form Start
     */
    public Loser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Perdiste = new javax.swing.JLabel();
        Tails = new javax.swing.JLabel();
        raya2 = new javax.swing.JLabel();
        raya1 = new javax.swing.JLabel();
        boom = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Perdiste1 = new javax.swing.JLabel();
        NuevoJuego = new javax.swing.JButton();
        menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 500));

        bg.setBackground(new java.awt.Color(255, 0, 0));
        bg.setPreferredSize(new java.awt.Dimension(800, 500));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Perdiste.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        Perdiste.setForeground(new java.awt.Color(255, 255, 255));
        Perdiste.setText("P E R D I S T E");
        jPanel1.add(Perdiste, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        Tails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tails_special_stage_falling_gif__by_foxeygamer87sonic_dg96uso-fullview-removebg-preview (1).png"))); // NOI18N
        jPanel1.add(Tails, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 760, -1));

        raya2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lovepik-black-brushes-brushes-brushes-elements-png-image_400808292_wh1200-removebg-preview.png"))); // NOI18N
        jPanel1.add(raya2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

        raya1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lovepik-black-brushes-brushes-brushes-elements-png-image_400808292_wh1200-removebg-preview.png"))); // NOI18N
        jPanel1.add(raya1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        boom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/istockphoto-1371914725-612x612-removebg-preview.png"))); // NOI18N
        jPanel1.add(boom, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));

        Perdiste1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        Perdiste1.setForeground(new java.awt.Color(255, 255, 255));
        Perdiste1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Perdiste1.setText("VUELVE A INTENTARLO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Perdiste1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Perdiste1)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 760, 50));

        NuevoJuego.setBackground(new java.awt.Color(0, 153, 0));
        NuevoJuego.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        NuevoJuego.setForeground(new java.awt.Color(255, 255, 255));
        NuevoJuego.setText("NUEVO JUEGO");
        NuevoJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoJuegoActionPerformed(evt);
            }
        });
        jPanel1.add(NuevoJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 380, -1));

        menu.setBackground(new java.awt.Color(0, 0, 0));
        menu.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        menu.setForeground(new java.awt.Color(255, 255, 255));
        menu.setText("MENU DE INICIO");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        jPanel1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 380, -1));

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 760, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        Start menu = new Start();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuActionPerformed

    private void NuevoJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoJuegoActionPerformed
        New_game game = new New_game();
        game.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_NuevoJuegoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NuevoJuego;
    private javax.swing.JLabel Perdiste;
    private javax.swing.JLabel Perdiste1;
    private javax.swing.JLabel Tails;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel boom;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton menu;
    private javax.swing.JLabel raya1;
    private javax.swing.JLabel raya2;
    // End of variables declaration//GEN-END:variables
}
