/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MetroInterfaz;

import LogicaJuego.Juego;
/**
 *
 * @author ile1
 */
public class New_game extends javax.swing.JFrame {

    int mouseX, mouseY;
    
    public New_game() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Columnas = new javax.swing.JLabel();
        Minas = new javax.swing.JLabel();
        NumMinas = new javax.swing.JTextField();
        filas = new javax.swing.JLabel();
        listo = new javax.swing.JLabel();
        jSpinner_Columna = new javax.swing.JSpinner();
        jSpinner_Filas = new javax.swing.JSpinner();
        paint1 = new javax.swing.JLabel();
        paint2 = new javax.swing.JLabel();
        paint3 = new javax.swing.JLabel();
        paint4 = new javax.swing.JLabel();
        Boom = new javax.swing.JLabel();
        Boom1 = new javax.swing.JLabel();
        Boom2 = new javax.swing.JLabel();
        traza_negra = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 500));

        bg.setBackground(new java.awt.Color(255, 102, 0));
        bg.setPreferredSize(new java.awt.Dimension(800, 500));
        bg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bgMouseDragged(evt);
            }
        });
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
        });
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 226));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Columnas.setFont(new java.awt.Font("Impact", 0, 28)); // NOI18N
        Columnas.setForeground(new java.awt.Color(0, 0, 0));
        Columnas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Columnas.setText("COLUMNAS");
        Columnas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(Columnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 130, 50));

        Minas.setFont(new java.awt.Font("Impact", 0, 28)); // NOI18N
        Minas.setForeground(new java.awt.Color(0, 0, 0));
        Minas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Minas.setText("MINAS");
        Minas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(Minas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 140, 50));

        NumMinas.setBackground(new java.awt.Color(255, 255, 255));
        NumMinas.setForeground(new java.awt.Color(0, 0, 0));
        NumMinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumMinasActionPerformed(evt);
            }
        });
        jPanel1.add(NumMinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        filas.setFont(new java.awt.Font("Impact", 0, 28)); // NOI18N
        filas.setForeground(new java.awt.Color(0, 0, 0));
        filas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        filas.setText("FILAS");
        filas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(filas, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 130, 50));

        listo.setFont(new java.awt.Font("Impact", 0, 28)); // NOI18N
        listo.setForeground(new java.awt.Color(255, 255, 255));
        listo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listo.setText("¡LISTO!");
        listo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listoMouseClicked(evt);
            }
        });
        jPanel1.add(listo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 130, 40));

        jSpinner_Columna.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jSpinner_Columna.setModel(new javax.swing.SpinnerNumberModel(3, 3, 10, 1));
        jPanel1.add(jSpinner_Columna, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 60, 30));

        jSpinner_Filas.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jSpinner_Filas.setModel(new javax.swing.SpinnerNumberModel(3, 3, 10, 1));
        jPanel1.add(jSpinner_Filas, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 60, 30));

        paint1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/png-clipart-poster-decorations-white-paint-removebg-preview.png"))); // NOI18N
        jPanel1.add(paint1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        paint2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/png-clipart-poster-decorations-white-paint-removebg-preview.png"))); // NOI18N
        jPanel1.add(paint2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, -1));

        paint3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/png-clipart-poster-decorations-white-paint-removebg-preview.png"))); // NOI18N
        jPanel1.add(paint3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        paint4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/png-clipart-poster-decorations-white-paint-removebg-preview.png"))); // NOI18N
        jPanel1.add(paint4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        Boom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Boom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/istockphoto-1371914725-612x612-removebg-preview.png"))); // NOI18N
        jPanel1.add(Boom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 390, -1));

        Boom1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Boom1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/istockphoto-1371914725-612x612-removebg-preview.png"))); // NOI18N
        jPanel1.add(Boom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 390, -1));

        Boom2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Boom2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/istockphoto-1371914725-612x612-removebg-preview.png"))); // NOI18N
        jPanel1.add(Boom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, -1));

        traza_negra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lovepik-black-brushes-brushes-brushes-elements-png-image_400808292_wh1200-removebg-preview.png"))); // NOI18N
        jPanel1.add(traza_negra, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 150, 120));

        jButton2.setBackground(new java.awt.Color(255, 255, 226));
        jButton2.setFont(new java.awt.Font("Impact", 0, 22)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("<<REGRESAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 30));

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 760, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_bgMousePressed

    private void bgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseX, y - mouseY);
                
    }//GEN-LAST:event_bgMouseDragged

    private void listoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listoMouseClicked
        Juego juego = new Juego();
        juego.seleccionarModoJuego();
    }//GEN-LAST:event_listoMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void NumMinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumMinasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumMinasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Boom;
    private javax.swing.JLabel Boom1;
    private javax.swing.JLabel Boom2;
    private javax.swing.JLabel Columnas;
    private javax.swing.JLabel Minas;
    private javax.swing.JTextField NumMinas;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel filas;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner_Columna;
    private javax.swing.JSpinner jSpinner_Filas;
    private javax.swing.JLabel listo;
    private javax.swing.JLabel paint1;
    private javax.swing.JLabel paint2;
    private javax.swing.JLabel paint3;
    private javax.swing.JLabel paint4;
    private javax.swing.JLabel traza_negra;
    // End of variables declaration//GEN-END:variables
}
