/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MetroInterfaz;

/**
 *
 * @author ile1
 */
public class Winner extends javax.swing.JFrame {

    /**
     * Creates new form Start
     */
    public Winner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Ganaste = new javax.swing.JLabel();
        Animales1 = new javax.swing.JLabel();
        Animales2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Ganaste2 = new javax.swing.JLabel();
        NuevoJuego = new javax.swing.JButton();
        Menu = new javax.swing.JButton();
        paint1 = new javax.swing.JLabel();
        paint2 = new javax.swing.JLabel();
        paint3 = new javax.swing.JLabel();
        paint4 = new javax.swing.JLabel();
        Grass1 = new javax.swing.JLabel();
        Grass2 = new javax.swing.JLabel();
        Grass3 = new javax.swing.JLabel();
        Grass4 = new javax.swing.JLabel();
        Grass5 = new javax.swing.JLabel();
        tails = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 500));

        bg.setBackground(new java.awt.Color(51, 255, 51));
        bg.setPreferredSize(new java.awt.Dimension(800, 500));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ganaste.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        Ganaste.setForeground(new java.awt.Color(0, 0, 0));
        Ganaste.setText("G A N A S T E");
        jPanel1.add(Ganaste, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        Animales1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/5dfdb9625e600-removebg-preview.png"))); // NOI18N
        jPanel1.add(Animales1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        Animales2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/_2.png"))); // NOI18N
        jPanel1.add(Animales2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));

        Ganaste2.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        Ganaste2.setForeground(new java.awt.Color(255, 255, 255));
        Ganaste2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ganaste2.setText("¡ ¡ ¡ FELICIDADES ! ! !");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Ganaste2, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Ganaste2)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 760, 50));

        NuevoJuego.setBackground(new java.awt.Color(0, 153, 0));
        NuevoJuego.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        NuevoJuego.setForeground(new java.awt.Color(255, 255, 255));
        NuevoJuego.setText("NUEVO JUEGO");
        jPanel1.add(NuevoJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 380, -1));

        Menu.setBackground(new java.awt.Color(0, 0, 0));
        Menu.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        Menu.setForeground(new java.awt.Color(255, 255, 255));
        Menu.setText("MENU DE INICIO");
        jPanel1.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 380, -1));

        paint1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/png-clipart-poster-decorations-white-paint-removebg-preview.png"))); // NOI18N
        jPanel1.add(paint1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        paint2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/png-clipart-poster-decorations-white-paint-removebg-preview.png"))); // NOI18N
        jPanel1.add(paint2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        paint3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/png-clipart-poster-decorations-white-paint-removebg-preview.png"))); // NOI18N
        jPanel1.add(paint3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        paint4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/png-clipart-poster-decorations-white-paint-removebg-preview.png"))); // NOI18N
        jPanel1.add(paint4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        Grass1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/grass-background-design-template-vector-21307391-removebg-preview (1).png"))); // NOI18N
        jPanel1.add(Grass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, 90, -1));

        Grass2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/grass-background-design-template-vector-21307391-removebg-preview (1).png"))); // NOI18N
        jPanel1.add(Grass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, -1));

        Grass3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/grass-background-design-template-vector-21307391-removebg-preview (1).png"))); // NOI18N
        jPanel1.add(Grass3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        Grass4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/grass-background-design-template-vector-21307391-removebg-preview (1).png"))); // NOI18N
        jPanel1.add(Grass4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, -1, -1));

        Grass5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/grass-background-design-template-vector-21307391-removebg-preview (1).png"))); // NOI18N
        jPanel1.add(Grass5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, -1, -1));

        tails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tails-sprite-sonic-the-hedgehog-png-favpng-4v5Sz99z4E9agfD1uvLHZ6HQ5-removebg-preview.png"))); // NOI18N
        jPanel1.add(tails, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 760, -1));

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 760, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Animales1;
    private javax.swing.JLabel Animales2;
    private javax.swing.JLabel Ganaste;
    private javax.swing.JLabel Ganaste2;
    private javax.swing.JLabel Grass1;
    private javax.swing.JLabel Grass2;
    private javax.swing.JLabel Grass3;
    private javax.swing.JLabel Grass4;
    private javax.swing.JLabel Grass5;
    private javax.swing.JButton Menu;
    private javax.swing.JButton NuevoJuego;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel paint1;
    private javax.swing.JLabel paint2;
    private javax.swing.JLabel paint3;
    private javax.swing.JLabel paint4;
    private javax.swing.JLabel tails;
    // End of variables declaration//GEN-END:variables
}
